apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubernetes-dashboard

resources:
  - recommended.yaml
  - admin-user.yaml

secretGenerator:
  - name: kubernetes-dashboard-certs
    files:
      - secret/certs/dashboard.crt
      - secret/certs/dashboard.csr
      - secret/certs/dashboard.key
generatorOptions:
  disableNameSuffixHash: true
